### ISSUE TITLE
现在无法看到图像，请检查！

### ISSUE THREAD

**Issue by starjason** [AliyunContainerService/monitoring-sample#1]
现在grafana里面无法看到图像，显示为 no datapoints  请检查！

**Comment by denverdino** [comment]
在Ubuntu上是工作的，您是使用CentOS吗？如果是这个问题正在排查。

**Comment by starjason** [comment]
ubuntu14 和centos7 都试过了 都无法正常 ！

**Comment by denverdino** [comment]
您的Docker版本是？我验证过 Ubuntu 14.04 上面 Docker 1.10和1.9.1 都是没有问题的，谢谢

**Comment by starjason** [comment]
root@ip-10-23-20-52:/home/ubuntu# docker -v
Docker version 1.11.0, build 4dc5990
root@ip-10-23-20-52:/home/ubuntu# docker-compose -v
docker-compose version 1.6.2, build 4d72027
root@ip-10-23-20-52:/home/ubuntu# cat /etc/issue
Ubuntu 14.04.2 LTS \n \l
无法显示数据和图像！

**Comment by yanchanghai** [comment]
这个版本的cAdvisor支持Docker1.9.1, Docker 1.10, Docker 1.11需要升级cAdvisor到v0.23.0

**Comment by starjason** [comment]
将docker-compose.yml里的cAdvisor升级   image: google/cadvisor:v0.23.0
 docker-compose up时报错
grafana_1   | 2016/05/06 02:33:08 [I] Created default admin user: admin
grafana_1   | 2016/05/06 02:33:08 [I] Listen: http://0.0.0.0:3000
influxsrv_1 | => Waiting for confirmation of InfluxDB service startup ...
config_1    | tput: No value for $TERM and no -T specified
config_1    | tput: No value for $TERM and no -T specified
config_1    | InfluxDB: Database cadvisor created
config_1    | tput: No value for $TERM and no -T specified
config_1    | tput: No value for $TERM and no -T specified
config_1    | InfluxDB: Database cadvisor user cadvisor created
influxsrv_1 | {"status":"ok"}
influxsrv_1 | => Creating database: cadvisor
influxsrv_1 | database cadvisor exists
influxsrv_1 | exec /usr/bin/influxdb -config=${CONFIG_FILE}
config_1    | tput: No value for $TERM and no -T specified
config_1    | tput: No value for $TERM and no -T specified
config_1    | Grafana: Data source cadvisor created
config_1    | {"slug":"container-activity","status":"success","version":0}
ubuntu_config_1 exited with code 0
grafana_1   | 2016/05/06 02:33:29 [I] Completed / 302 Found in 352.149µs
grafana_1   | 2016/05/06 02:33:29 [T] auto-login cookie cleared: admin
grafana_1   | 2016/05/06 02:33:36 [I] Completed /db/cadvisor/series 400 Bad Request in 355.864498ms
grafana_1   | 2016/05/06 02:33:36 [I] Completed /db/cadvisor/series 400 Bad Request in 411.890929ms
grafana_1   | 2016/05/06 02:33:36 [I] Completed /db/cadvisor/series 400 Bad Request in 414.085028ms
grafana_1   | 2016/05/06 02:33:36 [I] Completed /db/cadvisor/series 400 Bad Request in 418.019769ms
cadvisor_1  | E0506 02:34:07.435396       1 memory.go:91] failed to write stats to influxDb - 404 page not found
cadvisor_1  | E0506 02:35:07.520604       1 memory.go:91] failed to write stats to influxDb - 404 page not found

**Comment by denverdino** [comment]
cadvisor:v0.23.0 需要配合 Influxdb 0.9

已经更新所有Docker Image，docker-compose模板，和配置脚本支持  Influxdb 0.9

在 CentOS/Ubuntu 的 Docker 1.10.3做过验证

**Comment by starjason** [comment]
图像现在能正常显示了，还有2个问题：
1、docker-compose里的cadvisor版本还是v0.20.5 。
2、container_name无法正常显示名字，显示的却是id。

**Comment by denverdino** [comment]
1. v0.20.5 和 v0.23 都是可以使用的，更新docker-compose到v0.23
2. 这个需要看看相应Docker Engine版本和cAdvisor的兼容性。
