### ISSUE TITLE
docker-compose和跨节点部署

### ISSUE THREAD

**Issue by orientzc** [AliyunContainerService/monitoring-sample#2]
感谢提供了一个可执行的容器监控方案，但是仍有一点不清楚。请问docker-compose中设置label(aliyun.global:'true')之后，阿里云是如何实现的跨节点动态伸缩部署。

**Comment by denverdino** [comment]
阿里云提供了自己的编排引擎，在对Docker Compose/Swarm兼容的前提下实现了对跨节点通信，动态伸缩，全局服务等能力。谢谢

**Comment by orientzc** [comment]
非常感谢~~~
