### ISSUE TITLE
cadvisor报错

### ISSUE THREAD

**Issue by orientzc** [AliyunContainerService/monitoring-sample#4]
您好~请问docker logs查看cadvisor，有报错：devicemapper filesystem stats will not be reported: unable to find thin_ls binary？（此时cadvisor正常启动）
![erro_cadvisor](https://cloud.githubusercontent.com/assets/17718632/21343720/115373c8-c6d3-11e6-89ec-6cb826af3bd9.png)

**Comment by denverdino** [comment]
CAdvisor的问题，应该已经修复了 Fixed in https://github.com/google/cadvisor/pull/1476

你能试一下 v0.24.1 吗？欢迎Pull request

**Comment by denverdino** [comment]
Fixed

**Comment by orientzc** [comment]
万分感谢
